{
 "title": "Performance",
 "time": { "from": "2024-04-05T02:38:19.289Z", "to": "2024-06-06T22:19:15.449Z" },
 "templating": {
  "list": [
   {
    "name": "users",
    "label": "User",
    "query": "SELECT DISTINCT user_name\nFROM events\nWHERE $__timeFilter(timestamp)\n  AND user_name IS NOT NULL"
   },
   {
    "name": "tasks",
    "label": "Task",
    "query": "SELECT DISTINCT task_id\nFROM events\nWHERE $__timeFilter(timestamp) \n  AND task_id IS NOT NULL"
   }
  ]
 },
 "panels": [
  {
   "title": "Annotations speed (objects / h), per user",
   "type": "timeseries",
   "description": "Objects created or modified, per hour",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  toDate(timestamp) AS date,\n  user_name,\n  sum(JSONExtractUInt(payload, 'working_time')) / 1000 / 3600 as wt\nFROM events\nWHERE $__timeFilter(timestamp)\n  AND task_id IN (${tasks})\nGROUP BY date, user_name"
    },
    {
     "rawSql": "SELECT\n  toDate(timestamp) AS date,\n  user_name,\n  SUM(count)\nFROM events\nWHERE $__timeFilter(timestamp)\n  AND task_id IN (${tasks})\n  AND scope IN ('create:shapes', 'update:shapes')\nGROUP BY date, user_name"
    }
   ]
  },
  {
   "title": "Working time (min) per job",
   "type": "barchart",
   "description": "Total time spent on a job, time spent drawing objects (create or edit), and time spent using AI tools",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  job_id,\n  sum(JSONExtractUInt(payload, 'working_time')) / 1000 / 60 as \"total\"\nFROM events\nWHERE job_id IS NOT NULL\n  AND $__timeFilter(timestamp)\n  AND user_name IN (${users})\n  AND task_id IN (${tasks})\nGROUP BY job_id\nORDER BY job_id ASC"
    },
    {
     "rawSql": "SELECT\n  job_id,\n  sum(JSONExtractUInt(payload, 'working_time')) / 1000 / 60 as \"draw\"\nFROM events\nWHERE job_id IS NOT NULL\n  AND (scope='draw:object' OR obj_name LIKE 'cvat-brush-tools%')\n  AND $__timeFilter(timestamp)\n  AND user_name IN (${users})\n  AND task_id IN (${tasks})\nGROUP BY job_id"
    },
    {
     "rawSql": "SELECT\n  job_id,\n  sum(JSONExtractUInt(payload, 'working_time')) / 1000 / 60 as \"interact\"\nFROM events\nWHERE job_id IS NOT NULL\n  AND neighbor(obj_val, -1)='Interact'\n  AND $__timeFilter(timestamp)\n  AND user_name IN (${users})\n  AND task_id IN (${tasks})\nGROUP BY job_id"
    }
   ]
  },
  {
   "title": "Annotation speed (objects / h), per job",
   "type": "barchart",
   "description": "(Net number of annotated objects in job) / (total working time)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  job_id,\n  wt,\n  if( deleted_obj IS NULL, 0, deleted_obj ) as deleted_obj\nFROM\n(\n  SELECT\n      job_id,\n      sum(JSONExtractUInt(payload, 'working_time')) / 1000 / 3600 as wt\n      FROM events\n    WHERE $__timeFilter(timestamp)\n      AND user_name IN (${users})\n      AND task_id IN (${tasks})\n      AND job_id IS NOT NULL\n    GROUP BY job_id\n) AS A\nFULL OUTER JOIN\n(\n  SELECT\n    job_id,\n    if( sum(count) IS NULL, 0, sum(count) ) as deleted_obj\n    FROM events\n  WHERE $__timeFilter(timestamp)\n    AND user_name IN (${users})\n    AND task_id IN (${tasks})\n    AND scope = 'delete:shapes'\n    AND job_id IS NOT NULL\n  GROUP BY job_id\n) AS B\nON A.job_id = B.job_id\nORDER BY job_id ASC"
    },
    {
     "rawSql": "SELECT\n  job_id,\n  if( created_obj IS NULL, 0, created_obj ) as created_obj\nFROM\n(\n  SELECT\n      job_id\n    FROM events\n    WHERE $__timeFilter(timestamp)\n      AND user_name IN (${users})\n      AND task_id IN (${tasks})\n      AND job_id IS NOT NULL\n    GROUP BY job_id\n) AS A\nFULL OUTER JOIN\n(\n  SELECT\n    job_id,\n    if( sum(count) IS NULL, 0, sum(count) ) as created_obj\n    FROM events\n  WHERE $__timeFilter(timestamp)\n    AND user_name IN (${users})\n    AND task_id IN (${tasks})\n    AND scope = 'create:shapes'\n    AND job_id IS NOT NULL\n  GROUP BY job_id\n) AS B\nON A.job_id = B.job_id"
    },
    {
     "rawSql": "SELECT\n  job_id,\n  if( obj_val IS NULL, 'new', obj_val ) as state\nFROM\n(\n  SELECT\n      job_id,\n      FROM events\n    WHERE $__timeFilter(timestamp)\n      AND user_name IN (${users})\n      AND task_id IN (${tasks})\n      AND job_id IS NOT NULL\n    GROUP BY job_id\n) AS A\nFULL OUTER JOIN\n(\n  SELECT DISTINCT ON (job_id, obj_name)\n    job_id, obj_val\n    FROM events\n    WHERE scope = 'update:job'\n    AND obj_name in ('state')\n    ORDER BY timestamp DESC\n) AS B\nON A.job_id = B.job_id"
    }
   ]
  },
  {
   "title": "Average annotation time (s), per class",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT  \n  JSONExtractUInt(payload, 'working_time') / 1000 as wt,\n  JSONExtractString(payload, 'label'),\n  if( neighbor(obj_name,1) LIKE 'cvat-brush-tools%', neighbor(JSONExtractUInt(payload, 'working_time') / 1000, 1), 0 ) as next1,\n  if( neighbor(obj_name,-1) LIKE 'cvat-brush-tools%', neighbor(JSONExtractUInt(payload, 'working_time') / 1000, -1), 0 ) as prev1\nFROM events\nWHERE $__timeFilter(timestamp)\n    AND (user_name IN (${users}) OR user_name = 'All')\n    AND (task_id IN (${tasks}, -1) OR -1 in (${tasks}))"
    }
   ]
  }
 ]
}